# Kubernetes Secrets Template for Phase 2
# Replace the placeholder values with actual secrets before deployment

apiVersion: v1
kind: Secret
metadata:
  name: google-ai-secrets
  namespace: voice-agent-phase2
type: Opaque
data:
  # Base64 encoded Google Cloud credentials
  # echo -n "your-google-credentials-json" | base64
  google-credentials.json: "PLACEHOLDER_GOOGLE_CREDENTIALS_BASE64"
  
  # Base64 encoded Google Project ID
  # echo -n "your-project-id" | base64
  project-id: "PLACEHOLDER_PROJECT_ID_BASE64"

---
apiVersion: v1
kind: Secret
metadata:
  name: openai-secrets
  namespace: voice-agent-phase2
type: Opaque
data:
  # Base64 encoded OpenAI API key
  # echo -n "your-openai-api-key" | base64
  api-key: "PLACEHOLDER_OPENAI_API_KEY_BASE64"

---
apiVersion: v1
kind: Secret
metadata:
  name: voice-agent-tls
  namespace: voice-agent-phase2
type: kubernetes.io/tls
data:
  # TLS certificate and key (will be managed by cert-manager)
  tls.crt: "PLACEHOLDER_TLS_CERT_BASE64"
  tls.key: "PLACEHOLDER_TLS_KEY_BASE64" 