# Phase 2 GKE Secrets Reference
# This file shows the secrets that have been created

apiVersion: v1
kind: Secret
metadata:
  name: google-ai-secrets
  namespace: voice-agent-phase2
type: Opaque
data:
  # google-credentials.json: [base64 encoded service account key]
  project-id: c3BlZWNodG90ZXh0LTQ2NjgyMA==

---
apiVersion: v1
kind: Secret
metadata:
  name: openai-secrets
  namespace: voice-agent-phase2
type: Opaque
data:
  # api-key: [base64 encoded OpenAI API key]
